### PR TITLE
Fix out of sync creation of NetQASM LAST log

### PR DESCRIPTION
**Pull request by bkreynen**
While working on QNE we found an issue in NetQASM/SquidASM (the issue is on the NetQASM repo https://github.com/QuTech-Delft/netqasm/issues/55 ).

In short: the log files were being processed in both NetQASM and SquidASM due to which it happened out of order. To fix this a change was made to NetQASM (see PR: https://github.com/QuTech-Delft/netqasm/pull/56 for a detailed explanation) where the log files are now copied in NetQASM instead. Although these changes in SquidASM are not strictly required (NetQASM will just overwrite the log files SquidASM puts in LAST). For cleanliness I removed the calls in SquidASM.

### CODE REVIEW

**Comment by bkreynen** [comment]
Not entirely sure why this pipeline is failing. I tested with a PR with 0 changes as well and the pipeline still failed

**Review by bvdvecht — DISMISSED** [review]

**Comment by bvdvecht** [comment]
It looks like the issue with the example pipeline is related to the `pydantic` dependency version. The CI uses pydantic 2.X, which apparently breaks things that worked on 1.X. Changing `setup.cfg` such that pydantic is limited to `<2.0` should fix this. 
@bkreynen  Could you add another commit with this small change?

**Comment by bkreynen** [comment]
Thanks @bvdvecht  I pushed a fix

**Review by bvdvecht — APPROVED** [review]

**Comment by bvdvecht** [comment]
Thanks @bkreynen ! Merged.

**Pull request merged**
